force-app/main/default/objects/Barbecue_Budget__c/Barbecue_Budget__c.object-meta.xml
<CustomObject>
    <label>Presupuesto Asado</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Presupuestos Asados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Barbecue_Budget__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Representa la fecha y hora de finalización del presupuesto del asado.</description>
    <inlineHelpText>Ingrese la fecha y hora en que finaliza el presupuesto del asado.</inlineHelpText>
    <label>Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Barbecue_Budget__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Representa la fecha y hora de inicio del presupuesto del asado.</description>
    <inlineHelpText>Ingrese la fecha y hora en que inicia el presupuesto de asado.</inlineHelpText>
    <label>Inicio</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Barbecue_Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Nuevo&quot;</defaultValue>
    <description>Representa el estado del presupuesto de asado. Se actualiza automáticamente según el flujo del proceso.</description>
    <inlineHelpText>Seleccione el estado actual del presupuesto.</inlineHelpText>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>En curso de aprobación</fullName>
            </value>
            <value>
                <fullName>Programado</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CancelBarbecueBudgetsBatch.cls
public with sharing class CancelBarbecueBudgetsBatch implements Database.Batchable<SObject>, Database.Stateful {

    public Database.QueryLocator start(Database.BatchableContext BC) {
        // Consulta para obtener los presupuestos de asado que no hayan tenido lugar en la fecha prevista
        String query = 'SELECT Id, Status__c, Start__c, End__c FROM Barbecue_Budget__c WHERE End__c < TODAY AND Status__c != \'Completado\'';
        System.debug('query: ' + query);
        return Database.getQueryLocator(query);
    }

    // Método para actualizar los presupuestos de asado a 'Cancelado'
    public void execute(Database.BatchableContext BC, List<Barbecue_Budget__c> scope) {
        for (Barbecue_Budget__c budget : scope) {
            budget.Status__c = 'Cancelado';
        }
        update scope;
    }

    public void finish(Database.BatchableContext BC) {
        
    }
}